over_episode = 100;
max_steps = 13000/over_episode;
x_limit = 2000/over_episode;
figure(5);
grid on;
hold on;
 plot(mean(reshape(avg_reward_QQ_2, over_episode, [])),...
       'DisplayName','Q-learning with longer exploration phase');
plot(mean(reshape(importdata('data_sarsa/avg_reward_sarsa_2.mat'), over_episode, [])),...
      'DisplayName','SARSA with longer exploration phase');
% plot(mean(reshape(importdata('data_variation/avg_rewards_var_1.mat'), over_episode, [])),...
%      'DisplayName','Q-learning \epsilon 0.5');
% plot(mean(reshape(importdata('data_variation/avg_rewards_var_2.mat'), over_episode, [])),...
%      'DisplayName','Q-learning \epsilon 0.3');
% plot(mean(reshape(importdata('data_variation/avg_rewards_var_3.mat'), over_episode, [])),...
%      'DisplayName','Q-learning \epsilon 0.1');
% plot(mean(reshape(importdata('data_variation/avg_rewards_var_4.mat'), over_episode, [])),...
%      'DisplayName','Q-learning \epsilon 0.01'); 
% 
% plot(mean(reshape(importdata('data_sarsa/avg_reward_SARSA_var_1.mat'), over_episode, [])),...
%      'DisplayName','SARSA \epsilon 0.5'); 
% plot(mean(reshape(importdata('data_sarsa/avg_reward_SARSA_var_2.mat'), over_episode, [])),...
%      'DisplayName','SARSA \epsilon 0.3'); 
% plot(mean(reshape(importdata('data_sarsa/avg_reward_SARSA_var_3.mat'), over_episode, [])),...
%      'DisplayName','SARSA \epsilon 0.1');
% plot(mean(reshape(importdata('data_sarsa/avg_reward_SARSA_var_4.mat'), over_episode, [])),...
%      'DisplayName','SARSA \epsilon 0.01'); 
% plot(mean(reshape(importdata('data_variation/avg_rewards_var_4.mat'), over_episode, [])),...
%      'DisplayName','\epsilon 0.01');
% plot(mean(reshape(importdata('data_variation/avg_rewards_var_5.mat'), over_episode, [])),...
%      'DisplayName','\epsilon 0.0');
hold off;
h_legend = legend('-DynamicLegend', 'Location','southeast');
set(h_legend,'FontSize',14);
xlabel(['Training Episodes (x', num2str(over_episode),')']);
ylabel('Average maximum absolute difference in Q');
%xlim([0 x_limit]);
ylim([-60 6]);
